// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: searchItem.proto

package searchItem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSearchItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductName    string `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SellerName     string `protobuf:"bytes,2,opt,name=seller_name,json=sellerName,proto3" json:"seller_name,omitempty"`
	ExhibitionDate string `protobuf:"bytes,3,opt,name=exhibition_date,json=exhibitionDate,proto3" json:"exhibition_date,omitempty"`
	UpdateDate     string `protobuf:"bytes,4,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	Category       int32  `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
	RankingFilter  int32  `protobuf:"varint,6,opt,name=ranking_filter,json=rankingFilter,proto3" json:"ranking_filter,omitempty"`
	Page           int32  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetSearchItem) Reset() {
	*x = GetSearchItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSearchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchItem) ProtoMessage() {}

func (x *GetSearchItem) ProtoReflect() protoreflect.Message {
	mi := &file_searchItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchItem.ProtoReflect.Descriptor instead.
func (*GetSearchItem) Descriptor() ([]byte, []int) {
	return file_searchItem_proto_rawDescGZIP(), []int{0}
}

func (x *GetSearchItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *GetSearchItem) GetSellerName() string {
	if x != nil {
		return x.SellerName
	}
	return ""
}

func (x *GetSearchItem) GetExhibitionDate() string {
	if x != nil {
		return x.ExhibitionDate
	}
	return ""
}

func (x *GetSearchItem) GetUpdateDate() string {
	if x != nil {
		return x.UpdateDate
	}
	return ""
}

func (x *GetSearchItem) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *GetSearchItem) GetRankingFilter() int32 {
	if x != nil {
		return x.RankingFilter
	}
	return 0
}

func (x *GetSearchItem) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*ResponseResult `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	TotalNum int32             `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchItem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchItem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_searchItem_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResponse() []*ResponseResult {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SearchResponse) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

type ResponseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SellerName  string `protobuf:"bytes,3,opt,name=seller_name,json=sellerName,proto3" json:"seller_name,omitempty"`
	Stocks      int32  `protobuf:"varint,4,opt,name=stocks,proto3" json:"stocks,omitempty"`
	Price       int32  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl    string `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Comment     string `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	Category    int32  `protobuf:"varint,8,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *ResponseResult) Reset() {
	*x = ResponseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchItem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseResult) ProtoMessage() {}

func (x *ResponseResult) ProtoReflect() protoreflect.Message {
	mi := &file_searchItem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseResult.ProtoReflect.Descriptor instead.
func (*ResponseResult) Descriptor() ([]byte, []int) {
	return file_searchItem_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseResult) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ResponseResult) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ResponseResult) GetSellerName() string {
	if x != nil {
		return x.SellerName
	}
	return ""
}

func (x *ResponseResult) GetStocks() int32 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

func (x *ResponseResult) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ResponseResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ResponseResult) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ResponseResult) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

var File_searchItem_proto protoreflect.FileDescriptor

var file_searchItem_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x68, 0x69,
	0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x65, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x25,
	0x0a, 0x0e, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x5a, 0x0a, 0x0e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x22, 0xf4, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x3e, 0x0a, 0x0b,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x0f, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_searchItem_proto_rawDescOnce sync.Once
	file_searchItem_proto_rawDescData = file_searchItem_proto_rawDesc
)

func file_searchItem_proto_rawDescGZIP() []byte {
	file_searchItem_proto_rawDescOnce.Do(func() {
		file_searchItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_searchItem_proto_rawDescData)
	})
	return file_searchItem_proto_rawDescData
}

var file_searchItem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_searchItem_proto_goTypes = []interface{}{
	(*GetSearchItem)(nil),  // 0: GetSearchItem
	(*SearchResponse)(nil), // 1: SearchResponse
	(*ResponseResult)(nil), // 2: ResponseResult
}
var file_searchItem_proto_depIdxs = []int32{
	2, // 0: SearchResponse.response:type_name -> ResponseResult
	0, // 1: SearchItems.SearchItem:input_type -> GetSearchItem
	1, // 2: SearchItems.SearchItem:output_type -> SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_searchItem_proto_init() }
func file_searchItem_proto_init() {
	if File_searchItem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_searchItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSearchItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searchItem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searchItem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_searchItem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchItem_proto_goTypes,
		DependencyIndexes: file_searchItem_proto_depIdxs,
		MessageInfos:      file_searchItem_proto_msgTypes,
	}.Build()
	File_searchItem_proto = out.File
	file_searchItem_proto_rawDesc = nil
	file_searchItem_proto_goTypes = nil
	file_searchItem_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchItemsClient is the client API for SearchItems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchItemsClient interface {
	SearchItem(ctx context.Context, in *GetSearchItem, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchItemsClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchItemsClient(cc grpc.ClientConnInterface) SearchItemsClient {
	return &searchItemsClient{cc}
}

func (c *searchItemsClient) SearchItem(ctx context.Context, in *GetSearchItem, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/SearchItems/SearchItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchItemsServer is the server API for SearchItems service.
type SearchItemsServer interface {
	SearchItem(context.Context, *GetSearchItem) (*SearchResponse, error)
}

// UnimplementedSearchItemsServer can be embedded to have forward compatible implementations.
type UnimplementedSearchItemsServer struct {
}

func (*UnimplementedSearchItemsServer) SearchItem(context.Context, *GetSearchItem) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchItem not implemented")
}

func RegisterSearchItemsServer(s *grpc.Server, srv SearchItemsServer) {
	s.RegisterService(&_SearchItems_serviceDesc, srv)
}

func _SearchItems_SearchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchItemsServer).SearchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchItems/SearchItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchItemsServer).SearchItem(ctx, req.(*GetSearchItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchItems_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SearchItems",
	HandlerType: (*SearchItemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchItem",
			Handler:    _SearchItems_SearchItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searchItem.proto",
}
