// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.2
// source: ranking.proto

package ranking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRankItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category int32 `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetRankItem) Reset() {
	*x = GetRankItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ranking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankItem) ProtoMessage() {}

func (x *GetRankItem) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankItem.ProtoReflect.Descriptor instead.
func (*GetRankItem) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *GetRankItem) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *GetRankItem) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type RankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*RankingResult `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	TotalNum int32            `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
}

func (x *RankResponse) Reset() {
	*x = RankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ranking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResponse) ProtoMessage() {}

func (x *RankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResponse.ProtoReflect.Descriptor instead.
func (*RankResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *RankResponse) GetResponse() []*RankingResult {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RankResponse) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

type RankingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Price       int32  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl    string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Category    int32  `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *RankingResult) Reset() {
	*x = RankingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ranking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingResult) ProtoMessage() {}

func (x *RankingResult) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingResult.ProtoReflect.Descriptor instead.
func (*RankingResult) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *RankingResult) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RankingResult) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *RankingResult) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RankingResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RankingResult) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

var File_ranking_proto protoreflect.FileDescriptor

var file_ranking_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x57,
	0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x22, 0xa0, 0x01, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x36, 0x0a, 0x09, 0x52, 0x61,
	0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65,
	0x6d, 0x1a, 0x0d, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ranking_proto_rawDescOnce sync.Once
	file_ranking_proto_rawDescData = file_ranking_proto_rawDesc
)

func file_ranking_proto_rawDescGZIP() []byte {
	file_ranking_proto_rawDescOnce.Do(func() {
		file_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(file_ranking_proto_rawDescData)
	})
	return file_ranking_proto_rawDescData
}

var file_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ranking_proto_goTypes = []interface{}{
	(*GetRankItem)(nil),   // 0: GetRankItem
	(*RankResponse)(nil),  // 1: RankResponse
	(*RankingResult)(nil), // 2: RankingResult
}
var file_ranking_proto_depIdxs = []int32{
	2, // 0: RankResponse.response:type_name -> RankingResult
	0, // 1: RankItems.RankItem:input_type -> GetRankItem
	1, // 2: RankItems.RankItem:output_type -> RankResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ranking_proto_init() }
func file_ranking_proto_init() {
	if File_ranking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ranking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ranking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ranking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ranking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ranking_proto_goTypes,
		DependencyIndexes: file_ranking_proto_depIdxs,
		MessageInfos:      file_ranking_proto_msgTypes,
	}.Build()
	File_ranking_proto = out.File
	file_ranking_proto_rawDesc = nil
	file_ranking_proto_goTypes = nil
	file_ranking_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RankItemsClient is the client API for RankItems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankItemsClient interface {
	RankItem(ctx context.Context, in *GetRankItem, opts ...grpc.CallOption) (*RankResponse, error)
}

type rankItemsClient struct {
	cc grpc.ClientConnInterface
}

func NewRankItemsClient(cc grpc.ClientConnInterface) RankItemsClient {
	return &rankItemsClient{cc}
}

func (c *rankItemsClient) RankItem(ctx context.Context, in *GetRankItem, opts ...grpc.CallOption) (*RankResponse, error) {
	out := new(RankResponse)
	err := c.cc.Invoke(ctx, "/RankItems/RankItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankItemsServer is the server API for RankItems service.
type RankItemsServer interface {
	RankItem(context.Context, *GetRankItem) (*RankResponse, error)
}

// UnimplementedRankItemsServer can be embedded to have forward compatible implementations.
type UnimplementedRankItemsServer struct {
}

func (*UnimplementedRankItemsServer) RankItem(context.Context, *GetRankItem) (*RankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RankItem not implemented")
}

func RegisterRankItemsServer(s *grpc.Server, srv RankItemsServer) {
	s.RegisterService(&_RankItems_serviceDesc, srv)
}

func _RankItems_RankItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankItemsServer).RankItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RankItems/RankItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankItemsServer).RankItem(ctx, req.(*GetRankItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _RankItems_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RankItems",
	HandlerType: (*RankItemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RankItem",
			Handler:    _RankItems_RankItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking.proto",
}
